authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('log_user/', views.login_user, name='login')
]
 

pokedex/urls.py
from pokedex import views
from django.urls import path

app_name = "pokedex"
urlpatterns = [
    path("", views.listar_pokemon, name="listar_pokemon"),
    path("crear/", views.crear_pokemon, name="crear_pokemon")
]

pokedjango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokedex/', include('pokedex.urls')),
    path('authentication/', include('authentication.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

pokedex/models.py
from django.db import models

# Create your models here.

class Pokemon(models.Model):
    IDpoke = models.IntegerField()
    Descripcion = models.CharField(max_length=300)
    Peso = models.DecimalField(decimal_places=2, max_digits=2)
    Altura = models.DecimalField(decimal_places=2, max_digits=2)
        

pokedex/forms.py
from django import forms

class CrearPokemonForm(forms.Form):
    IDpoke = forms.IntegerField(label='ID Pokemon')
    Descripcion = forms.CharField(label='Descripcion Pokemon')
    Peso = forms.DecimalField(label='Peso (Kg)', min_value=20.0)
    Altura = forms.DecimalField(label='Altura (M)', min_value=20.0)

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def login_user(request):
    user = authenticate(
        username = request.POST['username'],
        password = request.POST['password']
    )
    if user is not None :
        print(type(user))
        login(request, user) # Crea sesion 
        return HttpResponseRedirect(reverse('pokedex:listar_pokemon'))
    else:
        return HttpResponse('No existe usuario', status=403)

def login_view(request):
    return render(request, 'authentication/login.html') 

pokedex/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Pokemon
from .forms import CrearPokemonForm

# Create your views here.

def listar_pokemon(request):
    pokemons = Pokemon.objects.all()
    context = {
            'lista_pokemons': pokemons,
            'crear_form': CrearPokemonForm()
        }
    return render(request, 'pokedex/index.html', context)

def crear_pokemon(request):
    if request.method == 'POST':
        form = CrearPokemonForm(request.POST)
        if form.is_valid():
            pokemon = Pokemon(
                IDpoke = form.IDpoke,
                Descripcion = form.Descripcion,
                Peso = form.Peso,
                Altura = form.Altura
            )
            pokemon.save()
        return HttpResponseRedirect(reverse('pokedex:listar_pokemon'))

authentication/templates/authentication/login.html
<form action="{% url 'authentication:login' %}" method="POST">
  {% csrf_token %}
  <input type="text" name="username" id="username" /><label for="username"
    >username</label
  ><br />
  <input type="text" name="password" id="password" /><label for="password"
    >contraseña</label
  ><br />
  <input type="submit" value="Ingresar" />
</form>

pokedex/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PokeDjango</title>
</head>
<body>
    {% load static %}
    <link rel="stylesheet" href="{% static "pokedex/style/estilobase.css"%}">
    <header class="header">
        <img src="{% static 'pokedex/img/pokeball.png' %}" alt="pokeball">
        <h1>PokeDjango</h1>
        <img src="{% static 'pokedex/img/pokeball.png' %}" alt="pokeball">
    </header>
    <h2 style="margin-top:2%">
    {% block subtitle %}{% endblock subtitle %}
    </h2>
    {% block content %}{% endblock content %}
    {% block footer %}{% endblock footer %}
</body>
</html>

pokedex/templates/pokedex/index.html
{% extends '../base.html' %}
{% block subtitle %}Lista General Pokemons{% endblock subtitle %}
{% block content %}
    {% csrf_token %}
    {{ crear_form }}
    <input type="submit" value="Crear Pokemon">
{% endblock content %}